@startuml

left to right direction

title  MapareVote - Use Case Diagram 

:Voter: -|> :User:
:Votemaker: -|> :User:
:Admin: -|> :User:

:Voter: --> (Vote)

:Votemaker: --> (Create vote)

(Create vote) <|-- (Create private vote)

(Create vote) <|-- (Create public vote)

:Votemaker: --> (Invite voter)

:Votemaker: --> (Consult intermediary results)

:Admin: --> (Ban Users due to inappropriate content)

(Vote) <. (Consult one's votes): extends

:Voter: --> (Consult one's votes)

(Consult one's votes) ..> (See the vote's results): include

Voter --> (Browse public votes)

(Vote) ..> (Browse public votes): extends

:User: --> (Change notification settings)

:Voter: --> (Consult private votes)

(Vote) ..> (Consult private votes): extends

:Voter: ---> (Share vote)

(Vote) <.. (Share vote): extends

(See the vote's results) <.. (Share vote): extends

:Voter: --> (Report vote)

@enduml