@startuml

title MapareVote - Class Diagram

package M {
    class Vote {
        int id
        String label
        LocalDate startDate
        LocalDate endDate
        String algo
        Boolean anonymous
    }
    
    class PrivateVote
    
    class Choice {
        int id
        int weight
    }
    
    class Ballot {
        int id
        LocalDateTime date
    }
    
    class User {
        int id
        String email
        String lastname
        String firstname
        String hashPassword
        String confirmationHash
        Boolean confirmed
        Boolean admin
        Boolean banned
    }
    
    class VotedVote {
        String token
    }
}


Choice "1..*" --* "1" Vote
Ballot "*" --* "1" Vote
Ballot "*" -- "*" Choice
Ballot "*" -- "0..1" User:Voter
Vote "*" --- "1" User:Votemaker
PrivateVote "1" *-- "*" User:Member
Vote "1"-- "*" VotedVote
VotedVote "*" -- "1" User
Vote <|-- PrivateVote

@enduml
